### ISSUE TITLE
daraku-mal-api.net no longer appears to be operating?

### ISSUE THREAD

**Issue by Mause** [Fribb/MyAnimeList.bundle#1]

**Comment by Fribb** [comment]
yup, take a look at this http://coding.fribbtastic.net/projects/myanimelistagent/ for the new version and new API location.

I moved to Github only for the unofficial appstore, but since the repository has been disabled ... I really can't do anything about it. So update to the new version and all should be fine

**Comment by Mause** [comment]
Aha, thankyou! :)
