### ISSUE TITLE
'No Results' for any possible search

### ISSUE THREAD

**Issue by typedrat** [Fribb/MyAnimeList.bundle#19]
It was working correctly before, but now whenever I search for a show to match, even when using the `myanimelist-id:` syntax, the plugin takes a very long time and then reports no results.

**Comment by typedrat** [comment]
The issue resolved itself after a few hours.

**Comment by Fribb** [comment]
There was an issue with the server the API was running on the last couple of days which made the API inaccessible. That issue was fixed yesterday and new requests were accepted again. But since plex caches those requests it can happen that it still not works until the cache is refreshed which was most likely the reason why it fixed itself.
