### ISSUE TITLE
Detect and fix episode offset

### ISSUE THREAD

**Issue by skyborgff** [Fribb/MyAnimeList.bundle#20]
Some episodes from the 2nd, 3rd, etc seasons instead of starting from 1 keep the counting from the previous season.
For example, episode 1 of attack on titan season 2 is labeled as episode 26, so the name mapping is wrong
This should be detected and fixed.

**Comment by Fribb** [comment]
The problem with that is how MAL organizes its shows. Each show has its individual metadata and episodes start at 1 again.

While there could be a way by requesting the sequel it wouldn't be a guarantee that that first sequel is also the actual direct sequel since I have seen entries with multiple sequels. The agent wouldn't be able to distinguish which one should be used without any guidance.

Another thing is that I would have to move through multiple individual entries and request the data which would be multiple API requests.

Those are currently all compensated by the API I am running in the background  but with the official API on the horizon this might not be a given anymore. So API requests need to be low.

Therefore, there is nothing to fix here since it is not how MAL organizes things.
