### ISSUE TITLE
Episode air date

### ISSUE THREAD

**Issue by NoOtakuSama** [Fribb/MyAnimeList.bundle#24]
Hey,

First of all, thanks for the great metadata agent, the new update really works great so far!
I do have one small suggestion if that's alright?

Adding an anime with unknown episode air dates, will use the current day. Wouldn't it be better to take for example the anime start/end date for the episodes? 

I like to make use of the 'Recently Released Episodes' in my Plex, especially for the now airing anime shows. But now it's getting filled in with a bunch of old anime I just added, which can be annoying.

What do you think?

**Comment by Fribb** [comment]
I think this is going into the wrong direction.

The aired date is unfortunately required for the "on deck" functionality. Without a date Plex wouldn't be able to know that there is a "next" episode available. For that reason I have added the current timestamp as aired date because most recently aired episodes don't have an aired date yet.

Using the first aired date of the anime could possibly end up that the episodes are not played in order because the first aired date is before the last episode with a date from MAL. but I haven't tested this because I didn't see a reason to. Maybe you could try this out and give some feedback.

The end date might work but as I said initially this is IMO going into the wrong direction.

What that would do is to create a situation that fits your needs and we are working around the actual issue, that myanimelist doesn't have the information you require.

So before the agent works around an inconvenience of the user, I think it would be better to actually add that information to myanimelist so that your situation works again. Another advantage of this would be that you are contributing to myanimelist by adding the information it lacks and therefore improving it for everyone.

I think we should first strive to make the information that MyAnimeList provides better and more complete before the agent does some gymnastics to not bother the user in some way because without some inconvenience, MyAnimeList won't get better, if that makes sense...

**Comment by NoOtakuSama** [comment]
Thanks for the fast reply!
Welp, seems like it's a difficult case! Some new released anime like Love Live All Stars also don't have any episode dates, I thought this was only for older-ish anime.. So my suggestion wouldn't matter much eitherway. :x 

The best fix would indeed be contributing to MyAnimeList so their database would be more.. complete.

Thanks for checking it out!
