### ISSUE TITLE
Instant "No Matches Found" on select shows.

### ISSUE THREAD

**Issue by ilikpoptarts** [Fribb/MyAnimeList.bundle#38]
Searching for a match instantly replies with "no matches found" no matter the search query. This only happens on select shows. I've provided the log of this behavior here > https://hastebin.com/raw/pitilatope . I took the liberty of dividing up the log into sections for each search, with an explanation of the basic behavior for each. All the shows in the log were added on the same date. I am stumped. Of 37 shows added, 8 show the behavior of instant "No Matches Found" like the 2 in the log.

This has happened previously to me, usually when adding more than 5 or so shows at once, the system _feels_ like it gets bogged and I'm only able to match a show after allowing the previously-matched show to load all its metadata, otherwise it will show no search results.

However, this is the first time that it has consistently had this behavior for over a day. I have tried reinstalling the agent, as well as cleaning database and bundles in plex settings. I have also tried matching these using [mal-<mal_id>] with the same results.

Thanks for all the support and the great agent.

edit: i'd also like to add, this was my reinstall experience: exit plex > delete MAL > launch plex & clean bundles > exit plex > put in new agent > launch plex. My main concern though, is that when I deleted the agent, and launched plex (with MAL agent deleted), the agent was still showing up in settings and available agents in the "Find Match" screen. Upon reinstalling, it also kept my previous settings in the MAL agent, which is understandable if settings are stored in a separate location. Is all of that expected behavior or did I miss something?

**Comment by Fribb** [comment]
When you have the "instant no matches found" then you also have a critical error so no surprises there because the Agent fails even before something the Agent is even doing something.

For "DanMachi" and "Management of a Novice Alchemist", could you share your file structure? According to the output you have or are requesting for Season 4 which isn't supported by the Agent, File organization should follow how MyAnimeList organizes it. That means each release needs to be its own Show in Plex.

That is, at least, the assumption of how the Agent works because the error is being thrown since it apparently cannot find either episode or Season 1 in the request you are making (this is for the .match file I implemented with the recent release).

weirdly enough, the "To your Eternity" has it as season 2 but there it works. Even stranger the "Management of a Novice Alchemist" has it as Season 1 but still fails.

I had this report on Reddit already but the Person never replied to my query for the file structure so I couldn't investigate this further without going on a wild goose chase.

A simple catch for that .match file part might suffice in this regard but I would like to be able to reproduce it.

**Comment by mondychan** [comment]
I cannot bring anything new to the table regarding debugging this problem, but I have experienced it numerous times myself

Coudnt find any other solution that removing the folder with the series from my main anime folder, 
remove the show (unmatched) inside plex, 
add the folder back and rescan, that would refresh the (possibly?) broken DB entry and would match as usual

**Comment by EZarnosky** [comment]
Normally my stuff matches (although I have hot had to rebuild my library in quite some time), but I have one "Do It Yourself!!" that will not match. Is the myanimelist-id: option still there, because that is not working either.

**Comment by Fribb** [comment]
> Normally my stuff matches (although I have hot had to rebuild my library in quite some time), but I have one "Do It Yourself!!" that will not match. Is the myanimelist-id: option still there, because that is not working either.

Please see the [Force a match](https://github.com/Fribb/MyAnimeList.bundle#force-a-match) section.

To keep it consistent I changed it from `myanimelist-id:XXXX` to `[mal-id:XXXXX]` so that it also works with the Absolute Series Scanner output.

**Comment by Fribb** [comment]
> I use this over HAMA since MAL ratings never populated for me on HAMA

HAMA uses a severely outdated and copied MAL code from this Agent, I have seen this stated a few times that people somehow got metadata with HAMA from MAL which just isn't possible because the API is offline for years now.

However, the MALAgent does accept Metadata from HAMA which might be something you could look into and try out by setting MAL as the main provider and setting HAMA as the secondary provider.

> Danmachi

Yeah, with the implementation of the Match file I specifically look for Season 1 Episode 1 to get the path to the match file. apparently, in some cases, this path or rather the media object does not contain Season 1 and/or Episode 1 which is why it fails.

I am wondering since you are organizing your files according to Seasonal structure how it would behave with the absolute structure.  Example, by using the [Absolute Series Scanner](https://github.com/ZeroQI/Absolute-Series-Scanner) and having your files organized like this:

- Gin no Guardian
   - Gin no Guardian - 01

Regardless of this outcome, I will add something this weekend to catch the error so that the Agent doesn't fail completely and prevent Metadata retrieval.

Still, the agent is designed to work only with Absolute order and one seasons so anything other you will not get episode metadata for other seasons.

**Comment by ilikpoptarts** [comment]
Just wanted to mention 2 things after reading this over again...
I did not have Gin no Guardian episode 1 in the folder, in fact I just had episode 4 since I was testing things. That may be the reason it couldn't match no matter what?

Also wanted to mention that I have had HAMA as a secondary agent selected for the past couple months and it has never provided metadata for a series. I added it under the mal agent mainly hoping for FanArtTV posters, or season posters and themes if I was lucky. From that experience, I assumed that there just wasn't a way for HAMA to know what series it needed to grab metadata for. But I suppose if it gets the mal ID it can do its matching magic. Maybe it's user error on my part somewhere.
[pic of agent settings](https://imgur.com/j1DZw9u)

**Comment by ilikpoptarts** [comment]
Oh boy. I think the problem has been found.

>Yeah, with the implementation of the Match file I specifically look for Season 1 Episode 1 to get the path to the match file. apparently, in some cases, this path or rather the media object does not contain Season 1 and/or Episode 1 which is why it fails.

If that is the case with match/search function in plex as well, that may have been the issue. It's very likely that my sonarr instance had simply not grabbed the first episode of those series yet. In fact, I added more series today. 3 of them didnt match, and came up with instant No Matches Found. After reading that comment I checked, and none of those 3 series had an EP1 in them yet. I then added the first episode to one of them, and it instantly found a match. Looking back now I can't believe I didn't think about that sooner. If that is the intended way of it working, might I suggest specifically stating on the readme page something along the lines of "it uses EP01 to match the show"?

**Comment by Fribb** [comment]
yeah, there is no difference between the automatic match and the manual match in terms of its functionality. The only difference is that you select the search result on a manual match instead of Plex deciding which one to pick.

Still, the issue is a problem I haven't thought about and will fix today. I will first have to check if a Season 1 exists (because that is the intended and recommended use for the agent) and when that is the case to pick whatever episode number is being used to find the match file.

This should then cover the bases and even if someone has a show that doesn't have an episode 1 yet or uses season organization it shouldn't fail completely.
