### ISSUE TITLE
Additional Metadata for Openings/Endings

### ISSUE THREAD

**Issue by Tama47** [Fribb/MyAnimeList.bundle#41]
It would be great if MAL could automatically retrieve the metadata for the Openings and Endings, which are typically listed. ~~Additionally, there are usually sample music tracks available that could potentially be used for the theme, similar to how the standard Plex theme operates.~~ Seems like this feature was already added in the latest release?

MAL Metadata:
<img width="800" alt="Screenshot 2023-03-06 at 3 38 30 PM" src="https://user-images.githubusercontent.com/96937943/223282237-3169deca-e57f-411c-bd48-ce409314fcf4.png">
<img width="800" alt="Screenshot 2023-03-06 at 3 38 49 PM" src="https://user-images.githubusercontent.com/96937943/223282239-f75462a1-d8d9-409c-bb2b-a214ffc6b937.png">
Desired Results:
<img width="800" alt="Screenshot 2023-03-06 at 4 32 23 PM" src="https://user-images.githubusercontent.com/96937943/223287976-65c822c3-3f8b-4c31-b48f-be1a0f5b5f2e.png">

Edit: When there are more than one Openings/Endings Theme
<img width="800" alt="Screenshot 2023-03-06 at 8 02 12 PM" src="https://user-images.githubusercontent.com/96937943/223317659-f553fa33-c25d-4f25-a549-654faefd78bf.png">
<img width="800" alt="Screenshot 2023-03-06 at 8 02 36 PM" src="https://user-images.githubusercontent.com/96937943/223317713-204cbbcf-b2df-47ff-ba2f-3b2108a0f394.png">
<img width="800" alt="Screenshot 2023-03-06 at 8 03 35 PM" src="https://user-images.githubusercontent.com/96937943/223317832-24d0d2b6-87e1-4351-859a-d5c8c3b841d2.png">

Also would be nice to be able to choose the languages. For example, if these were based on when you choose "Main" or "English" in the Preferred Title Language.

**Comment by Fribb** [comment]
Plex does not have a way to save the Metadata from MAL for Openings and endings. This would already be a reason against this feature because there was no real way for the metadata to be stored in plex.

Looking at the JikanAPI [One Piece for example](https://api.jikan.moe/v4/anime/21/themes) only provides a list of "openings" and "endings".

While this could be requested, there is still nothing to hold that information specifically. Your desired result would be to add that information to specific episodes which isn't a good idea because, again, they are just lists. So I would need to invent some form of convention specifically for a dedicated season. For example, if a new opening is being added I would need to provide enough buffer to not force a user to constantly push the endings "down the road", what I mean is that if you have 5 openings and 5 endings then someone could think that S00E01-E05 are openings and E06-10 are endings. If you get an opening 6 the metadata would be applied to the 6th episode without any information to the user. So everything would shift. To compensate for this I could force "blocks" so S00E01-99 are reserved for Openings and 100-199 are reserved for Endings.

But if you now look into the API response linked above, you will see that this list has a few things to note:

1. it is just a list of text
2. it is not ordered

MAL is notorious for not being consistent so I wouldn't think that this list is going to be consistent either. This means that anything could be in there which is making it hard to work with.

For example, I would have to go to lengths to specifically validate that everything is correct in that list and with hundreds of thousands of entries on MAL this is quite impossible.

This could also mean that one day you have it all ordered correctly but another day something changes and everything isn't anymore leading to more questions for the agent, and myself, to answer.

So, from this point of view, I would close this issue as "not planned" because there is nothing for the information to be stored in and putting it to specific episodes would be more trouble than it is worth it.

However, what would make sense, what I already thought about, is adding videos like trailers to your library item as extras. from what I know, this is actually possible since MAL and the JikanAPI provide Youtube links for those things. This then could also include the rest of the "videos" on MAL.

But I would see that as a separate issue.

**Comment by Tama47** [comment]
I see where you're coming from and why this might be hard to implement. I guess I'll just continue doing it manually for now.

Also, I believe Absolute Series Scanner already reserves Episodes 101-150 for OPs and Episodes 151-200 for EDs.
<img width="397" alt="Screenshot 2023-03-06 at 8 53 46 PM" src="https://user-images.githubusercontent.com/96937943/223324131-2313e015-fdef-4f31-8072-1a9577f77495.png">
But the idea of adding the rest of the "videos" on MAL is interesting, as that would includes the OPs/EDs as well.

> I would see that as a separate issue.

Should I open a new issue for it?

**Comment by Fribb** [comment]
> Should I open a new issue for it?

I already did with #42

**Comment by Tama47** [comment]
Thanks!
