### ISSUE TITLE
Feature request: English show name auto matching

### ISSUE THREAD

**Issue by bsamsom** [Fribb/MyAnimeList.bundle#46]
When adding dubbed versions of shows such as "Moribito - Guardian of the Spirit" the shows will have 0 matches from the agent using the MyAnimeList.net agent.

I need to go in and manually match the show using their non-English name ("Seirei no Moribito" in this example)

This is probably due to the way the search works on MyAnimeList.net
https://myanimelist.net/anime/1827/Seirei_no_Moribito?q=Moribito%3A%20Guardian%20of%20the%20Spirit&cat=anime
![image](https://github.com/Fribb/MyAnimeList.bundle/assets/16020228/0e62a909-58cf-4f36-af1e-3c4ba084201c)
i.e if you search a show name in English it finds the correct results but displays it via the non-English name.

**Comment by Fribb** [comment]
It's been a while since I implemented this but shouldn't this already be working?

Looking at the code and the agents settings there are two things you can configure:

1. Preferred Title Language
2. Exclude the Preferred title from search (Search will use the main title for matching)

So if you set the first one to English and disable the second, you should be able to match it with the English title.

But those are settings that would only apply to your whole library automatically.

**Comment by bsamsom** [comment]
it looks like those are the settings im using:
![image](https://github.com/Fribb/MyAnimeList.bundle/assets/16020228/5dc7ae7f-7620-400d-a023-8ebf82d1c1ab)
but there is no match when it is added to the library: 
![image](https://github.com/Fribb/MyAnimeList.bundle/assets/16020228/9a2ed537-640e-4bce-b287-5900cc597cf1)

**Comment by bsamsom** [comment]
whops, i miss read that, you said disable not enable.
